### ISSUE TITLE
What env you used?

### ISSUE THREAD

**Issue by Crystalxd** [valgur/SuperGluePretrainedNetwork#3]
I used gcc compiler which is gcc7, and used cxx14 standard, but I got error when I make:

/home/dl/projects/SuperGluePretrainedNetwork/cpp/superglue.cpp:5:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/superglue.dir/build.make:81: recipe for target 'CMakeFiles/superglue.dir/superglue.cpp.o' failed
make[2]: *** [CMakeFiles/superglue.dir/superglue.cpp.o] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/superglue.dir/all' failed
make[1]: *** [CMakeFiles/superglue.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

Than I modified <filesystem> to <experimental/filesystem>
"namespace fs = std::experimental::filesystem;" to "namespace fs = std::experimental::filesystem;"
but I got follow error:

/home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp: In function ‘std::tuple<at::Tensor, at::Tensor, at::Tensor> unpack_result(const c10::IValue&)’:
/home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp:20:53: error: converting to ‘std::tuple<at::Tensor, at::Tensor, at::Tensor>’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {at::Tensor&, at::Tensor&, at::Tensor&}; <template-parameter-2-2> = void; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’
           dict.at("descriptors").toTensorVector()[0]};
                                                     ^
/home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp: In function ‘int main(int, const char**)’:
/home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp:48:25: error: ‘weakly_canonical’ is not a member of ‘fs’
   auto executable_dir = fs::weakly_canonical(fs::path(argv[0])).parent_path();
                         ^
make[2]: *** [CMakeFiles/superglue.dir/superglue.cpp.o] Error 1
make[1]: *** [CMakeFiles/superglue.dir/all] Error 2
make: *** [all] Error 2

BTW, my libtorch version is 1.6.0+cu101 (PyTorch too.)

**Comment by zzl20** [comment]
> I used gcc compiler which is gcc7, and used cxx14 standard, but I got error when I make:
> 
> /home/dl/projects/SuperGluePretrainedNetwork/cpp/superglue.cpp:5:10: fatal error: filesystem: No such file or directory
> #include
> ^~~~~~~~~~~~
> compilation terminated.
> CMakeFiles/superglue.dir/build.make:81: recipe for target 'CMakeFiles/superglue.dir/superglue.cpp.o' failed
> make[2]: *** [CMakeFiles/superglue.dir/superglue.cpp.o] Error 1
> CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/superglue.dir/all' failed
> make[1]: *** [CMakeFiles/superglue.dir/all] Error 2
> Makefile:102: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> Than I modified to <experimental/filesystem>
> "namespace fs = std::experimental::filesystem;" to "namespace fs = std::experimental::filesystem;"
> but I got follow error:
> 
> /home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp: In function ‘std::tuple<at::Tensor, at::Tensor, at::Tensor> unpack_result(const c10::IValue&)’:
> /home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp:20:53: error: converting to ‘std::tuple<at::Tensor, at::Tensor, at::Tensor>’ from initializer list would use explicit constructor ‘constexpr std::tuple< >::tuple(_UElements&& ...) [with _UElements = {at::Tensor&, at::Tensor&, at::Tensor&}; = void; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’
> dict.at("descriptors").toTensorVector()[0]};
> ^
> /home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp: In function ‘int main(int, const char**)’:
> /home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp:48:25: error: ‘weakly_canonical’ is not a member of ‘fs’
> auto executable_dir = fs::weakly_canonical(fs::path(argv[0])).parent_path();
> ^
> make[2]: *** [CMakeFiles/superglue.dir/superglue.cpp.o] Error 1
> make[1]: *** [CMakeFiles/superglue.dir/all] Error 2
> make: *** [all] Error 2
> 
> BTW, my libtorch version is 1.6.0+cu101 (PyTorch too.)
不用管那个filesysterm , 把两个模型携程绝对路径就行

**Comment by Crystalxd** [comment]
> > I used gcc compiler which is gcc7, and used cxx14 standard, but I got error when I make:
> > /home/dl/projects/SuperGluePretrainedNetwork/cpp/superglue.cpp:5:10: fatal error: filesystem: No such file or directory
> > #include
> > ^~~~~~~~~~~~
> > compilation terminated.
> > CMakeFiles/superglue.dir/build.make:81: recipe for target 'CMakeFiles/superglue.dir/superglue.cpp.o' failed
> > make[2]: *** [CMakeFiles/superglue.dir/superglue.cpp.o] Error 1
> > CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/superglue.dir/all' failed
> > make[1]: *** [CMakeFiles/superglue.dir/all] Error 2
> > Makefile:102: recipe for target 'all' failed
> > make: *** [all] Error 2
> > Than I modified to <experimental/filesystem>
> > "namespace fs = std::experimental::filesystem;" to "namespace fs = std::experimental::filesystem;"
> > but I got follow error:
> > /home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp: In function ‘std::tuple<at::Tensor, at::Tensor, at::Tensor> unpack_result(const c10::IValue&)’:
> > /home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp:20:53: error: converting to ‘std::tuple<at::Tensor, at::Tensor, at::Tensor>’ from initializer list would use explicit constructor ‘constexpr std::tuple< >::tuple(_UElements&& ...) [with _UElements = {at::Tensor&, at::Tensor&, at::Tensor&}; = void; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’
> > dict.at("descriptors").toTensorVector()[0]};
> > ^
> > /home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp: In function ‘int main(int, const char**)’:
> > /home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp:48:25: error: ‘weakly_canonical’ is not a member of ‘fs’
> > auto executable_dir = fs::weakly_canonical(fs::path(argv[0])).parent_path();
> > ^
> > make[2]: *** [CMakeFiles/superglue.dir/superglue.cpp.o] Error 1
> > make[1]: *** [CMakeFiles/superglue.dir/all] Error 2
> > make: *** [all] Error 2
> > BTW, my libtorch version is 1.6.0+cu101 (PyTorch too.)
> > 不用管那个filesysterm , 把两个模型携程绝对路径就行

感谢！我把fs相关的换成绝对路径了，但是有这个错：
/home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp: In function ‘std::tuple<at::Tensor, at::Tensor, at::Tensor> unpack_result(const c10::IValue&)’:
/home/dl/liuxx/new_version/SuperGluePretrainedNetwork/cpp/superglue.cpp:20:53: error: converting to ‘std::tuple<at::Tensor, at::Tensor, at::Tensor>’ from initializer list would use explicit constructor ‘constexpr std::tuple< >::tuple(_UElements&& ...) [with _UElements = {at::Tensor&, at::Tensor&, at::Tensor&}; = void; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’
dict.at("descriptors").toTensorVector()[0]};
是和libtorch的版本有关系吗？

**Comment by zzl20** [comment]
你按照cpp文件夹中的readme下载那个里面的libtorch但是那个是cpu版本，gpu的话得需要1.5版本的,但是我GPU报错，你知道运行的第三个参数写多少吗

**Comment by Crystalxd** [comment]
我现在还没编译成功，这个错看起来可能不是libtorch问题，我也没搞懂是什么原因。第三个参数应该是一个可以自定义的宽度吧？用来缩放尺度？

**Comment by zzl20** [comment]
> 我现在还没编译成功，这个错看起来可能不是libtorch问题，我也没搞懂是什么原因。第三个参数应该是一个可以自定义的宽度吧？用来缩放尺度？

其实有那两个生成的模型就行了，剩下的自己弄就行我之前弄过好久没弄代码不知道哪里去了

**Comment by Crystalxd** [comment]
嗯。我这边问题解决了，在作者的代码上，使用gcc7 with cxx_14, libtorch1.6.0+cu101编译成功了，gpu版本也跑通了，效果挺不错的

**Comment by DHNicoles** [comment]
@Crystalxd  我按照作者给的步骤，python jit.py，但是报错了：

> Loaded SuperPoint model
Traceback (most recent call last):
  File "jit.py", line 7, in <module>
    superglue = SuperGlue({'weights': 'outdoor'}).eval()
  File "/root/anaconda2/envs/holc/lib/python3.7/site-packages/torch/jit/__init__.py", line 1453, in init_then_script
    original_init(self, *args, **kwargs)
  File "/workspace/vpas/cpp/SuperGluePretrainedNetwork-cpp/models/superglue.py", line 228, in __init__
    self.descriptor_dim, self.GNN_layers)
  File "/root/anaconda2/envs/holc/lib/python3.7/site-packages/torch/jit/__init__.py", line 1456, in init_then_script
    self.__dict__["_actual_script_module"] = torch.jit._recursive.create_script_module(self, stubs)
  File "/root/anaconda2/envs/holc/lib/python3.7/site-packages/torch/jit/_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/root/anaconda2/envs/holc/lib/python3.7/site-packages/torch/jit/_recursive.py", line 340, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/root/anaconda2/envs/holc/lib/python3.7/site-packages/torch/jit/_recursive.py", line 259, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
### RuntimeError: unknown:0: expecting kind 'variable' but found '.'
  File "/workspace/vpas/cpp/SuperGluePretrainedNetwork-cpp/models/superglue.py", line 141
    def forward(self, desc0, desc1):
        for i, layer in enumerate(self.layers):
            layer.attn.prob = []
            ~~~~~~~~~~ <--- HERE
            if self.names[i] == 'cross':
                src0, src1 = desc1, desc0

**Comment by Crystalxd** [comment]
@DHNicoles 用高版本的pytorch试试，我是用pytorch1.6.0+cuda101来转换的，1.2.0版本边上好像有bug

**Comment by DHNicoles** [comment]
嗯 我的机器环境版本的确优点低。
